### PR TITLE
#51 Fixed 'lambda' syntax error

### PR DESCRIPTION
**Pull request by keigezellig**

### CODE REVIEW

**Review by KeyWeeUsr — CHANGES_REQUESTED** [review]
Nope, this is a Python 2 quirk because the syntax in Py2 expects a tuple passed as a parameter:

    list(takewhile(lambda (x,y): [print(x, y) or True], enumerate([9,8,7])))

and unfortunately this raises an error in Py3.

Instead you'll need to accept only one parameter, the tuple, and then access specific element from it.

**Comment by keigezellig** [comment]
@KeyWeeUsr Hmm if this library should (still) support Python 2, then there is some workaround needed to make it compatible with Python 2 **and** Python 3.
What do you think?

**Comment by KeyWeeUsr** [comment]
@keigezellig Yes, there is one, I already suggested it in the last paragraph. You need to accept only one parameter (a tuple) and move the accessing of the element of the tuple to the lambda itself :)

**Review by tito — APPROVED** [review]

**Comment by tito** [comment]
Thanks for your PR, but i see it conflict and was fixed in master in a similar way.

**Pull request closed without merging**
